### ISSUE TITLE
running go 1.8

### ISSUE THREAD

**Issue by joeblew99** [tylerchr/examples#2]
is there an easy way to run go 1.8 on my mac ?

i have go 1.7 now and dont wish to screw that one up.

**Comment by bertoort** [comment]
```
go get golang.org/x/build/version/go1.8rc3
```
Then, use the go1.8rc3 command instead of the go command to use go1.8rc3.

https://golang.org/dl/#unstable

**Comment by tylerchr** [comment]
@berto Thank you for mentioning that, it hadn't occurred to me.
